# Generated by Django 3.2 on 2021-12-01 05:08

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T13_inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t13_title', models.CharField(max_length=30, verbose_name='題名')),
                ('t13_sentence', models.TextField(max_length=400, verbose_name='内容')),
                ('t13_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t13_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='T1_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_shop_name_prime', models.CharField(max_length=40, verbose_name='店名')),
                ('t1_address', models.CharField(max_length=200, verbose_name='住所')),
                ('t1_shop_sun', models.BooleanField(blank=True, null=True, verbose_name='日曜日')),
                ('t1_shop_mon', models.BooleanField(blank=True, null=True, verbose_name='月曜日')),
                ('t1_shop_tue', models.BooleanField(blank=True, null=True, verbose_name='火曜日')),
                ('t1_shop_wed', models.BooleanField(blank=True, null=True, verbose_name='水曜日')),
                ('t1_shop_tru', models.BooleanField(blank=True, null=True, verbose_name='木曜日')),
                ('t1_shop_fri', models.BooleanField(blank=True, null=True, verbose_name='金曜日')),
                ('t1_shop_sat', models.BooleanField(blank=True, null=True, verbose_name='土曜日')),
                ('t1_start_time', models.TimeField(verbose_name='注文開始時間')),
                ('t1_end_time', models.TimeField(verbose_name='注文終了時間')),
                ('t1_favorite_count', models.IntegerField(default=0, verbose_name='お気に入り数')),
                ('t1_tel_number', models.CharField(max_length=11, verbose_name='電話番号')),
                ('t1_shop_discribe', models.TextField(blank=True, max_length=200, null=True, verbose_name='説明')),
                ('t1_shop_name_sub', models.CharField(blank=True, max_length=30, null=True, verbose_name='サブ店名')),
                ('t1_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t1_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('t1_shop_photo_01', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真01')),
                ('t1_shop_photo_02', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真02')),
                ('t1_shop_photo_03', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真03')),
                ('t1_shop_photo_04', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真04')),
                ('t1_shop_photo_05', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真05')),
                ('t1_bank_name', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='金融機関名')),
                ('t1_bank_location', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='支店番号')),
                ('t1_bank_number', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='口座番号')),
                ('t1_review_ave', models.FloatField(blank=True, default=2.5, max_length=3, verbose_name='レビュー評価')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='T2_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t2_comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='コメント')),
                ('t2_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t2_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('t2_week', models.PositiveIntegerField(blank=True, choices=[(1, '日'), (2, '月'), (3, '火'), (4, '水'), (5, '木'), (6, '金'), (7, '土')], null=True, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='曜日')),
                ('t2_order_count', models.PositiveIntegerField(verbose_name='残り回数')),
                ('t1_shop_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='店舗ID')),
            ],
        ),
        migrations.CreateModel(
            name='T8_shop_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t8_shop_category_name', models.CharField(blank=True, max_length=40, verbose_name='カテゴリ名')),
                ('t8_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t8_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='T9_food_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t9_food_category_name', models.CharField(blank=True, max_length=40, verbose_name='カテゴリ名')),
                ('t9_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t9_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='T7_delivery_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t7_delivery_man_firstname', models.CharField(max_length=20, verbose_name='姓')),
                ('t7_delivery_man_lastname', models.CharField(max_length=20, verbose_name='名')),
                ('t7_delivery_man_tel', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='電話番号')),
                ('t7_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t7_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('t7_bank_name', models.CharField(max_length=20, null=True, verbose_name='金融機関名')),
                ('t7_bank_location', models.CharField(max_length=8, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='支店番号')),
                ('t7_bank_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='口座番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='T6_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t6_star', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='星')),
                ('t6_title', models.CharField(blank=True, max_length=40, null=True, verbose_name='タイトル')),
                ('t6_sentence', models.TextField(blank=True, max_length=400, null=True, verbose_name='本文')),
                ('t6_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t4_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('t1_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='T5_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t5_user_firstname', models.CharField(max_length=30, verbose_name='顧客姓')),
                ('t5_user_lastname', models.CharField(max_length=30, verbose_name='顧客名')),
                ('t5_address', models.CharField(max_length=70, verbose_name='住所')),
                ('t5_post', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('t5_tel_number', models.CharField(max_length=11, verbose_name='電話番号')),
                ('t5_landmark', models.TextField(blank=True, max_length=200, null=True, verbose_name='自宅の目印')),
                ('t5_allergy', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=300), blank=True, null=True, size=None, verbose_name='控えるべき食材')),
                ('t5_charge_tool', models.PositiveIntegerField(choices=[(1, '銀行'), (0, 'クレジットカード')], default=0, verbose_name='チャージ方法')),
                ('t5_charge_remain', models.IntegerField(blank=True, default=0, null=True, verbose_name='チャージ残高')),
                ('t5_credit_number', models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='カード番号')),
                ('t5_credit_limit', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='有効期限')),
                ('t5_credit_security', models.IntegerField(blank=True, null=True, verbose_name='セキュリティナンバー')),
                ('t5_bank_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='金融機関名')),
                ('t5_bank_location', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='支店番号')),
                ('t5_bank_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='口座番号')),
                ('t5_bank_password', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='口座暗証番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='T4_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t4_ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None, verbose_name='食材')),
                ('t4_food_photo_01', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真01')),
                ('t4_price', models.PositiveIntegerField(verbose_name='単価')),
                ('t4_food_name', models.CharField(max_length=40, verbose_name='料理名')),
                ('t4_food_discribe', models.TextField(blank=True, max_length=400, null=True, verbose_name='説明')),
                ('t4_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t4_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('t4_order_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='注文回数')),
                ('t1_shop_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='店舗ID')),
                ('t9_food_category_id', models.ManyToManyField(to='prime.T9_food_category', verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='T3_order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t3_amount', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('t3_delivery_date', models.DateTimeField(verbose_name='配達予定時刻')),
                ('t3_comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='コメント')),
                ('t3_payment', models.PositiveIntegerField(verbose_name='料金')),
                ('t3_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t3_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('t3_order_deliver_status', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1)], verbose_name='配送状態')),
                ('t2_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.t2_order', verbose_name='注文ID')),
                ('t4_food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.t4_food', verbose_name='料理ID')),
                ('t7_delivery_man_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.t7_delivery_man', verbose_name='配達員ID')),
            ],
        ),
        migrations.AddField(
            model_name='t2_order',
            name='t5_user_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='prime.t5_user', verbose_name='ユーザー'),
        ),
        migrations.CreateModel(
            name='T12_charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t12_charge_amount', models.PositiveIntegerField(default=0, verbose_name='チャージ額')),
                ('t12_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t12_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('t12_charge_remain_ex', models.IntegerField(default=0, verbose_name='チャージ後残高')),
                ('t5_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.t5_user', verbose_name='店舗ID')),
            ],
        ),
        migrations.CreateModel(
            name='T11_love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t11_create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t11_update_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('t1_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='店舗ID')),
                ('t5_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.t5_user', verbose_name='ユーザーID')),
            ],
        ),
    ]
