# Generated by Django 3.2 on 2021-11-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1_shop',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='t1_shop',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='t5_user',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='t5_user',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='t7_delivery_man',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='t7_delivery_man',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='t11_love',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
