# Generated by Django 3.2 on 2021-12-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t1_shop',
            name='t8_shop_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t8_shop_category', verbose_name='店舗カテゴリ'),
        ),
    ]
