# Generated by Django 3.2 on 2021-11-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0002_auto_20211119_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1_shop',
            name='t1_password',
        ),
    ]
