# Generated by Django 3.2 on 2021-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0003_auto_20211202_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='t7_delivery_man',
            name='t7_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='確認写真'),
        ),
    ]
