# Generated by Django 3.2 on 2021-11-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0003_remove_t1_shop_t1_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='t1_shop',
            name='t1_shop_photo_01',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真01'),
        ),
        migrations.AddField(
            model_name='t1_shop',
            name='t1_shop_photo_02',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真02'),
        ),
        migrations.AddField(
            model_name='t1_shop',
            name='t1_shop_photo_03',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真03'),
        ),
        migrations.AddField(
            model_name='t1_shop',
            name='t1_shop_photo_04',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真04'),
        ),
        migrations.AddField(
            model_name='t1_shop',
            name='t1_shop_photo_05',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真05'),
        ),
        migrations.AddField(
            model_name='t4_food',
            name='t4_food_photo_01',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真01'),
        ),
    ]
