# Generated by Django 3.2 on 2021-11-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0004_auto_20211119_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='t1_shop',
            name='t1_review_ave',
            field=models.FloatField(blank=True, default=2.5, max_length=3, verbose_name='レビュー評価'),
        ),
    ]
