# Generated by Django 3.2 on 2021-12-03 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prime', '0004_t7_delivery_man_t7_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t12_charge',
            name='t5_user_id',
        ),
        migrations.AddField(
            model_name='t12_charge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
