# Generated by Django 3.2 on 2021-12-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0005_auto_20211203_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t12_charge',
            name='t12_charge_remain_ex',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='チャージ後残高'),
        ),
        migrations.AlterField(
            model_name='t7_delivery_man',
            name='t7_photo',
            field=models.ImageField(upload_to='', verbose_name='確認写真'),
        ),
    ]
