# Generated by Django 3.2 on 2021-11-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0005_t1_shop_t1_review_ave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t9_food_category',
            old_name='t9_shop_category_name',
            new_name='t9_food_category_name',
        ),
    ]
