# Generated by Django 3.2 on 2021-11-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0006_rename_t9_shop_category_name_t9_food_category_t9_food_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1_shop',
            name='t1_end_time',
            field=models.TimeField(verbose_name='注文終了時間'),
        ),
        migrations.AlterField(
            model_name='t1_shop',
            name='t1_start_time',
            field=models.TimeField(verbose_name='注文開始時間'),
        ),
    ]
