# Generated by Django 3.2 on 2022-01-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0006_auto_20211203_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t12_charge',
            name='t12_charge_remain_ex',
        ),
    ]
