# Generated by Django 3.2 on 2021-11-25 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0007_auto_20211124_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t5_user',
            name='t10_area_id',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.SET_DEFAULT, to='prime.t10_area', verbose_name='エリア'),
        ),
    ]
