# Generated by Django 3.2 on 2021-11-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0009_alter_t5_user_t5_charge_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t5_user',
            name='t5_credit_security',
            field=models.PositiveIntegerField(null=True, verbose_name='セキュリティナンバー'),
        ),
        migrations.AlterField(
            model_name='t5_user',
            name='t5_post',
            field=models.CharField(max_length=7, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='t5_user',
            name='t5_tel_number',
            field=models.CharField(max_length=11, verbose_name='電話番号'),
        ),
    ]
