# Generated by Django 3.2 on 2022-01-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0009_alter_t1_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t2_order',
            name='t1_shop_id',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='店舗ID'),
        ),
    ]
