# Generated by Django 3.2 on 2022-01-24 02:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prime', '0011_remove_t2_order_t5_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='t2_order',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='t2_order',
            name='t2_week',
            field=models.PositiveIntegerField(choices=[(1, '日'), (2, '月'), (3, '火'), (4, '水'), (5, '木'), (6, '金'), (7, '土')], null=True, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='曜日'),
        ),
    ]
