# Generated by Django 3.2 on 2022-01-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0013_alter_t2_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='t2_order',
            name='t2_done',
            field=models.BooleanField(default=False, verbose_name='詳細注文済みか'),
        ),
    ]
