# Generated by Django 3.2 on 2021-11-26 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0013_alter_t5_user_t5_credit_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1_shop',
            name='t10_area_id',
            field=models.ForeignKey(default='未設定', on_delete=django.db.models.deletion.SET_DEFAULT, to='prime.t10_area', verbose_name='エリア'),
        ),
        migrations.AlterField(
            model_name='t1_shop',
            name='t1_tel_number',
            field=models.CharField(max_length=11, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='t5_user',
            name='t5_bank_name',
            field=models.CharField(max_length=20, null=True, verbose_name='金融機関名'),
        ),
        migrations.AlterField(
            model_name='t5_user',
            name='t5_credit_security',
            field=models.IntegerField(null=True, verbose_name='セキュリティナンバー'),
        ),
        migrations.AlterField(
            model_name='t7_delivery_man',
            name='t7_bank_name',
            field=models.CharField(max_length=20, null=True, verbose_name='金融機関名'),
        ),
    ]
