# Generated by Django 3.2 on 2022-01-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0014_t2_order_t2_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t11_love',
            name='t1_shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='t11_love',
            name='t5_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t5_user', verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='t13_inquiry',
            name='t13_title',
            field=models.CharField(max_length=30, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='t2_order',
            name='t1_shop_id',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='t3_order_detail',
            name='t2_order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t2_order', verbose_name='注文'),
        ),
        migrations.AlterField(
            model_name='t3_order_detail',
            name='t4_food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t4_food', verbose_name='料理'),
        ),
        migrations.AlterField(
            model_name='t3_order_detail',
            name='t7_delivery_man_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.t7_delivery_man', verbose_name='配達員'),
        ),
        migrations.AlterField(
            model_name='t4_food',
            name='t1_shop_id',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='t4_food',
            name='t4_food_photo_01',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='t5_user',
            name='t5_user_firstname',
            field=models.CharField(max_length=30, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='t5_user',
            name='t5_user_lastname',
            field=models.CharField(max_length=30, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='t6_review',
            name='t1_shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.t1_shop', verbose_name='店'),
        ),
        migrations.AlterField(
            model_name='t9_food_category',
            name='t9_food_category_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='食品カテゴリ名'),
        ),
    ]
