# Generated by Django 3.2 on 2022-01-25 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prime', '0017_auto_20220125_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t11_love',
            name='t5_user_id',
        ),
        migrations.AddField(
            model_name='t11_love',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
