# Generated by Django 3.2 on 2022-01-28 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prime', '0018_auto_20220125_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3_order_detail',
            name='t3_review_done',
            field=models.BooleanField(default=False, verbose_name='レビューしたか'),
        ),
        migrations.AddField(
            model_name='t3_order_detail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
