# Generated by Django 3.2 on 2022-01-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0019_auto_20220128_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t3_order_detail',
            name='t3_delivery_date',
            field=models.TimeField(verbose_name='配達予定時刻'),
        ),
    ]
