# Generated by Django 3.2 on 2022-02-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0021_auto_20220201_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t2_order',
            name='t2_done',
        ),
        migrations.AlterField(
            model_name='t2_order',
            name='t2_order_count',
            field=models.PositiveIntegerField(verbose_name='注文予定回数'),
        ),
    ]
