# Generated by Django 3.2 on 2022-02-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0022_auto_20220201_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t3_order_detail',
            name='t3_delivery_date',
        ),
        migrations.AddField(
            model_name='t2_order',
            name='t3_delivery_date',
            field=models.TimeField(default='00:00:00', verbose_name='配達予定時刻'),
        ),
    ]
