# Generated by Django 3.2 on 2022-02-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0023_auto_20220201_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t2_order',
            old_name='t3_delivery_date',
            new_name='t2_delivery_date',
        ),
    ]
