# Generated by Django 3.2 on 2022-02-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0024_rename_t3_delivery_date_t2_order_t2_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t3_order_detail',
            name='t3_order_deliver_status',
        ),
        migrations.AddField(
            model_name='t2_order',
            name='t2_order_deliver_status',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='配送状態'),
        ),
    ]
