# Generated by Django 3.2 on 2021-11-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'ユーザー'), ('2', '店舗'), ('3', '配達員')], max_length=1, verbose_name='user_type'),
        ),
    ]
