# Generated by Django 3.2 on 2021-11-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.ForeignKey(default='2359', on_delete=django.db.models.deletion.CASCADE, to='accounts.t10_area', verbose_name='エリア'),
        ),
    ]
